### ISSUE TITLE
Logo Asset

### ISSUE THREAD

**Issue by alabinjo** [Shopify/hatchful-design#11]
Got some feedback on the design:

- Many prefer the black color logo because it looks less childish. Let's figure out what we can do with the colors. 
- I would like to explore different font types and try lowercase letters

![image](https://user-images.githubusercontent.com/17554587/32149495-e0ed7daa-bcdb-11e7-91a0-f3a0d599d143.png)

**Comment by r36yang** [comment]
![image](https://user-images.githubusercontent.com/29125461/32149701-f3dc0604-bcde-11e7-923a-7efccb3b6b2d.png)

Here's a bit of an in-progress update with the mark – deciding if I want to add the feathers in. We will need a colored and black & white version regardless I think – def consider all lowercase letters, it's friendlier

**Comment by alabinjo** [comment]
I think without the feather is better. Less is more and it looks a bit cleaner. 

Do you think the icon is a bit too big?

**Comment by r36yang** [comment]
_I think without feather is better too, but it looks too much like a penguin, and Skye suggested the feather adds a lot of personality. The size of the icon will probably be adjusted and fine tuned based on the font / weight / size we pick so this isn't final :)_

**Comment by r36yang** [comment]
<img width="997" alt="hatch_video_assets" src="https://user-images.githubusercontent.com/29125461/32194199-0fc4eec4-bd90-11e7-9d9b-55f9d64f5bad.png">
Done (will add this to press kit)
