### ISSUE TITLE
Remove Furniture Category and Update Home & Garden 

### ISSUE THREAD

**Issue by alabinjo** [Shopify/hatchful-design#2]
# Task

- [ ] Remove "Furniture" category from list 
- [ ] Update "Home & Garden" with an icon more representative for home 

![screen shot 2017-10-19 at 5 42 02 pm](https://user-images.githubusercontent.com/17554587/31795490-fc50d596-b4f3-11e7-81bf-dbf00f72f1a4.png)

**Comment by r36yang** [comment]
I think this is done, "other" renamed to "all" and sorted to be first in the grid, and home & garden icon changed to furniture icon, furniture removed.
